### ISSUE TITLE
Missing has_excerpt filter?

### ISSUE THREAD

**Issue by gntech** [octopress/filters#1]
I have noticed that the filter "has_excerpt" is missing from this version of octopress-filters. It was present in the old octopress.

Is this by design? Has it been replaced by some other function?

**Comment by imathis** [comment]
Ah, good catch. I decided to do it a different way that a filter. I've just released 1.3.0 which will let you use `{{ post.excerpted }}` to determine if a post has been excerpted. No more need for filters. Check the docs (at the bottom) if you'd like to see an example of usage. Thanks for opening this issue!

**Comment by gntech** [comment]
Perfect! Works as a charm, thanks :)
